import {
    Code,
    Text,
    Title,
} from "@mantine/core";


export default function Bio() {
    return (
        <>
            <Title order={1}>About Me</Title>

            <Text>
                I'm Ben. You might also know me as <Code>Golf0ned</Code>.
            </Text>

            <Text>
                I'm a third year at <a href="https://www.northwestern.edu/">Northwestern University</a> studying Computer Science. My interests involve compilers and programming languages. I'm currently analyzing and optimizing LLVM-IR generated by Rust at <a href="https://users.cs.northwestern.edu/~simonec/Team.html">Northwestern's ARCANA Lab</a>. 
            </Text>
        </>
    );
}
